services:
  pss:
    image: noamzeise/protein-structure-storage
    ports:
      - "8000:5000"
  pc:
    image: noamzeise/protein-cache
    ports:
      - "6000:6000"
    depends_on:
      - mongo
    command: ["/wait-for-it.sh", "mongo:27017", "--", "python main.py"]
  mongo:
    image: mongo
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081