services:
  pss:
    image: harbor.peak.scot/jh03/protein-structure-storage
    ports:
      - "8000:5000"
    volumes:
      - ./config:/src/config/
  psp:
    image: harbor.peak.scot/jh03/protein-structure-prediction
    ports:
      - "7000:7000"
  pc:
    image: harbor.peak.scot/jh03/protein-cache
    ports:
      - "6000:6000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
