test-protein-structure-storage:
  stage: test
  image: python:3
  before_script:
    - cd protein-structure-storage
    - pip install -r requirements.txt
  script:
    - python -m unittest

build-and-deploy-job:
  stage: build
  image: docker
  services:
    - "docker:dind"
  script:
    - docker build -t $DOCKERHUB_USERNAME/protein-structure-storage:latest protein-structure-storage
    - docker build -t $DOCKERHUB_USERNAME/protein-cache:latest protein-cache
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_AUTHCODE
    - docker image push $DOCKERHUB_USERNAME/protein-structure-storage:latest
    - docker image push $DOCKERHUB_USERNAME/protein-cache:latest
  environment: production
  only:
    refs:
      - main