build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job tests something."

test-job2:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - cd protein-structure-storage
    - python -m unittest &> protein-structure-storage-unittest-report.txt

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
