# build-job:
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"

test-protein-structure-storage:
  stage: test
  image: python:3
  before_script:
    - ls
    - pip install -r requirements.txt
  script:
    - cd protein-structure-storage
    - python -m unittest

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production
