services:
  pss:
    build: protein-structure-storage
    ports:
      - "8000:5000"
  pc:
    build: protein-cache
    ports:
      - "7000:6000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081