services:
  pss:
    build: protein-structure-storage
    ports:
      - "8000:5000"
    volumes:
      - ./config:/src/config/
  pc:
    build: protein-cache
    ports:
      - "6000:6000"
    depends_on:
      - mongo
  psp:
    build: protein-structure-prediction
    ports:
      - "7000:7000"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081