apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pc
  name: pc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-only-default: "true"
        io.kompose.service: pc
    spec:
      containers:
        - image: noamzeise/protein-cache
          name: pc
          ports:
            - containerPort: 6000
              hostPort: 7000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pc
  name: pc
spec:
  type: NodePort
  ports:
    - name: "7000"
      port: 7000
      targetPort: 6000
  selector:
    io.kompose.service: pc
status:
  loadBalancer: {}
