apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy: {}
  template:
    metadata:
      labels:
        network/compose-only-default: "true"
        service: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    service: mongo
status:
  loadBalancer: {}
