apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: psp
  name: psp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: psp
  strategy: {}
  template:
    metadata:
      labels:
        service: psp
    spec:
      containers:
        - image: noamzeise/protein-structure-prediction
          name: psp
          ports:
            - containerPort: 7000
              hostPort: 7000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: psp
  name: psp
spec:
  type: NodePort
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
  selector:
    service: psp
status:
  loadBalancer: {}
