name: build+push

on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t pss protein-structure-storage 
      - run: docker build -t pc protein-cache
      - run: docker build -t psp protein-structure-prediction
      - run: docker image tag pss ${{ secrets.DOCKERHUB_USERNAME }}/protein-structure-storage:latest
      - run: docker image tag pc ${{ secrets.DOCKERHUB_USERNAME }}/protein-cache:latest
      - run: docker image tag psp ${{ secrets.DOCKERHUB_USERNAME }}/protein-structure-prediction:latest
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_AUTHCODE }}
      - run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/protein-structure-storage:latest
      - run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/protein-cache:latest
      - run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/protein-structure-prediction:latest
      - run: docker image tag pss harbor.peak.scot/${{ secrets.PEAK_HARBOR_USERNAME }}/protein-structure-storage:latest
      - run: docker image tag pc harbor.peak.scot/${{ secrets.PEAK_HARBOR_USERNAME }}/protein-cache:latest
      - run: docker image tag psp harbor.peak.scot/${{ secrets.PEAK_HARBOR_USERNAME }}/protein-structure-prediction:latest
      - run: docker login harbor.peak.scot -u ${{ secrets.PEAK_HARBOR_USERNAME }} -p ${{ secrets.PEAK_HARBOR_AUTHCODE }}
      - run: docker image push harbor.peak.scot/${{ secrets.PEAK_HARBOR_USERNAME }}/protein-structure-storage:latest
      - run: docker image push harbor.peak.scot/${{ secrets.PEAK_HARBOR_USERNAME }}/protein-cache:latest
      - run: docker image push harbor.peak.scot/${{ secrets.PEAK_HARBOR_USERNAME }}/protein-structure-prediction:latest
