name: build+push

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t pss protein-structure-storage 
      - run: docker build -t pc protein-cache
      - run: docker build -t psp protein-structure-prediction
      - run: docker image tag pss $DOCKERHUB_USERNAME/protein-structure-storage:latest
      - run: docker image tag pc $DOCKERHUB_USERNAME/protein-cache:latest
      - run: docker image tag psp $DOCKERHUB_USERNAME/protein-structure-prediction:latest
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_AUTHCODE
      - run: docker image push $DOCKERHUB_USERNAME/protein-structure-storage:latest
      - run: docker image push $DOCKERHUB_USERNAME/protein-cache:latest
      - run: docker image push $DOCKERHUB_USERNAME/protein-structure-prediction:latest
      - run: docker image tag pss harbor.peak.scot/$PEAK_HARBOR_USERNAME/protein-structure-storage:latest
      - run: docker image tag pc harbor.peak.scot/$PEAK_HARBOR_USERNAME/protein-cache:latest
      - run: docker image tag psp harbor.peak.scot/$PEAK_HARBOR_USERNAME/protein-structure-prediction:latest
      - run: docker login harbor.peak.scot -u $PEAK_HARBOR_USERNAME -p $PEAK_HARBOR_AUTHCODE
      - run: docker image push harbor.peak.scot/$PEAK_HARBOR_USERNAME/protein-structure-storage:latest
      - run: docker image push harbor.peak.scot/$PEAK_HARBOR_USERNAME/protein-cache:latest
      - run: docker image push harbor.peak.scot/$PEAK_HARBOR_USERNAME/protein-structure-prediction:latest
