name: test

on:
  push:
    branches: [main]

jobs:
  test-pss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd protein-structure-storage
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: python -m unittest
        
  test-psp:
        runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd protein-structure-prediction
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: python -m unittest
